services:
  db:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartcity_user -d smartcity"]
      interval: 10s
      timeout: 3s
      retries: 5
  backend:
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5050/"]
      interval: 10s
      timeout: 3s
      retries: 5
